In [1]:
import pandas as pd
from catboost import CatBoostRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import pickle

player_df = pd.read_csv('../data/model_dataset/player_df_dummies.csv', index_col='unique_id')

In [2]:
player_df.columns

Index(['Unnamed: 0', 'full_name', 'minutes', 'goals_scored', 'assists', 'bps',
       'selected_by_percent', 'previous_start_value', 'delta_value',
       'target_value', 'position_DEF', 'position_FWD', 'position_GK',
       'position_MID', 'teams_arsenal', 'teams_astonvilla',
       'teams_bournemouth', 'teams_brentford', 'teams_brighton&hovealbion',
       'teams_burnley', 'teams_cardiffcity', 'teams_chelsea',
       'teams_crystalpalace', 'teams_everton', 'teams_fulham',
       'teams_huddersfieldtown', 'teams_leedsunited', 'teams_leicestercity',
       'teams_liverpool', 'teams_manchestercity', 'teams_manchesterunited',
       'teams_newcastleunited', 'teams_norwichcity', 'teams_nottinghamforest',
       'teams_sheffieldunited', 'teams_southampton', 'teams_stokecity',
       'teams_swanseacity', 'teams_tottenhamhotspur', 'teams_watford',
       'teams_westbromwichalbion', 'teams_westhamunited',
       'teams_wolverhamptonwanderers'],
      dtype='object')

In [3]:
player_df.drop(columns=['target_value', 'Unnamed: 0']).head()

,full_name,minutes,goals_scored,assists,bps,selected_by_percent,previous_start_value,delta_value,position_DEF,position_FWD,...,teams_nottinghamforest,teams_sheffieldunited,teams_southampton,teams_stokecity,teams_swanseacity,teams_tottenhamhotspur,teams_watford,teams_westbromwichalbion,teams_westhamunited,teams_wolverhamptonwanderers
unique_id,,,,,,,,,,,,,,,,,,,,,
7-2017-18,héctorbellerín,3050.0,2.0,4.0,656.0,10.3,60.0,-1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
11-2017-18,robholding,819.0,0.0,1.0,196.0,0.7,50.0,-6.0,1,0,...,0,0,0,0,0,0,0,0,0,0
16-2017-18,mesutözil,2161.0,4.0,9.0,506.0,2.1,95.0,-2.0,0,0,...,0,0,0,0,0,0,0,0,0,0
18-2017-18,aaronramsey,1844.0,7.0,10.0,503.0,4.5,70.0,-2.0,0,0,...,0,0,0,0,0,0,0,0,0,0
21-2017-18,alexiwobi,1827.0,3.0,5.0,426.0,1.0,55.0,-4.0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
# Assuming player_df has the features and target column you want to use for training
# Replace 'target_column' with the name of your target column
features = player_df.drop(columns=['target_value', 'Unnamed: 0', 'full_name', 'bps', 'selected_by_percent'])
target = player_df['target_value']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

# Initialize the CatBoost regression model
model = CatBoostRegressor(iterations=1000,  # Adjust the number of iterations as needed
                          learning_rate=0.1,  # Adjust the learning rate as needed
                          depth=5,  # Adjust the depth of the trees as needed
                          loss_function='RMSE',  # Using Root Mean Squared Error as the loss function
                          random_seed=42)

# Fit the model to the training data
model.fit(X_train, y_train, verbose=100)  # You can adjust the verbose level to see more/less output during training

# Make predictions on the test data
y_pred = model.predict(X_test)

# Calculate the mean squared error to evaluate the model's performance
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

# Now, you can use the trained model (model) to make predictions on new data
# For example:
# new_data = pd.DataFrame(...)  # Create a new DataFrame with features for prediction
# predictions = model.predict(new_data)

0:	learn: 12.5169311	total: 60.4ms	remaining: 1m
100:	learn: 4.3634524	total: 105ms	remaining: 932ms
200:	learn: 3.7911322	total: 148ms	remaining: 590ms
300:	learn: 3.3680814	total: 195ms	remaining: 453ms
400:	learn: 3.0690114	total: 241ms	remaining: 360ms
500:	learn: 2.8045715	total: 287ms	remaining: 286ms
600:	learn: 2.5850001	total: 332ms	remaining: 220ms
700:	learn: 2.4053261	total: 382ms	remaining: 163ms
800:	learn: 2.2685345	total: 428ms	remaining: 106ms
900:	learn: 2.1348697	total: 474ms	remaining: 52ms
999:	learn: 2.0227415	total: 536ms	remaining: 0us
Mean Squared Error: 42.56764066996096

In [5]:
y_pred

array([ 55.64577867,  57.39677849,  48.33982935,  55.16875812,
        52.33337228,  58.3151863 ,  54.47979084,  73.0187356 ,
        54.4114348 ,  63.26396865,  56.53965138,  61.15992956,
        44.91222306,  52.45079298,  44.17247418,  52.98918888,
        49.9038465 ,  75.88745038,  63.73104345,  55.06639721,
        48.75799661,  47.18375618,  43.98971421,  44.32864612,
        69.05888122,  48.23717185,  50.56302849,  42.54940847,
        45.3401394 ,  45.97158094,  42.5695127 ,  52.42995695,
        47.67868026,  56.55240597,  44.36496158,  75.08316932,
        60.40385826,  67.41317871,  47.48416097,  46.2181553 ,
        59.22722094,  44.70385712,  51.4759154 ,  51.41192365,
        58.929162  ,  64.63514626,  49.70190772,  62.71261295,
        53.5749694 ,  52.90625169,  48.67037577,  49.17562441,
        49.31227317,  50.62468634,  49.66731995,  47.66030303,
        45.3672401 ,  47.65390989,  51.12115085,  57.87364001,
        57.41097958,  68.76554698,  56.01261159, 119.35357675,
        48.52254966,  54.83289025,  59.09831815,  49.20533788,
        46.46803248,  59.05076036,  55.74965366,  48.68051145,
        56.35456174,  62.99707859,  47.86268779,  58.94695463,
        89.00552966,  59.70920669,  48.39988094,  43.3980305 ,
        53.98290469,  46.6860823 ,  63.41089141,  44.60360174,
        49.59362302,  45.80135026,  59.62998005,  44.64165747,
        61.32491382,  51.43569345,  55.94977799,  58.07956339,
        70.5987928 ,  67.21283468,  63.55573988,  52.43244821,
        52.62660759,  48.37974132,  46.26865065,  45.64606867,
        51.35667371,  49.73550498,  59.69465822,  47.96275798,
        60.29170881,  81.54517172,  53.1274631 ,  55.05628589,
        61.3437319 ,  45.50701106,  51.99316426,  50.73397945,
        60.38997498,  57.92763641,  49.73994877,  45.78177318,
        48.95579074,  90.81048505,  49.23783495,  45.2118926 ,
        76.31326147,  60.63288953,  58.41357229,  44.45103571,
        46.44253268,  45.77185654,  64.38035553,  45.88490405,
        58.09368263,  46.61326609,  54.79902557,  68.71489537,
        55.49381559,  46.1677019 ,  53.07619042,  45.9021256 ,
        40.79034356,  75.93907702,  45.81547659,  48.77793243,
        67.14822674,  46.3339665 ,  54.87560888,  95.22125159,
        47.28757023,  47.75107741,  56.52505728,  49.86625283,
        54.8759001 ,  46.25482192,  47.70800415,  47.60967002,
        49.76287737,  59.74039926,  49.84348869,  45.73369736,
        48.13680333,  48.04975039,  59.5537415 ,  56.48581035,
        43.00579162,  51.78535605,  42.57430733,  43.76504678,
        56.77414499,  50.07861815,  59.0729066 ,  65.18758208,
        45.97840621,  44.79389609,  49.51047568, 112.54409761,
        54.7349372 ,  59.94396052,  51.17289375,  46.00920589,
        57.65542272,  52.45721702,  72.99205661,  59.35638201,
        44.52359293,  45.06033179,  82.49427681,  57.04533608,
        52.14400593,  46.80783427,  60.41087469,  60.95593613,
        67.62357255,  49.0401266 ,  54.4872134 , 112.68938733,
        59.35130667,  47.59777591,  44.96886499,  87.9185708 ,
        49.31250092,  49.61031514,  42.33670974,  92.49040981,
        47.11741148,  42.72925044,  45.84013314,  69.79012289,
        55.04812252, 108.45496984,  44.74829395,  54.24196406,
        52.14773072,  54.30661007,  43.20053733,  54.54888315,
        92.32309402,  68.73789905,  51.20505365,  46.65989237,
        58.31477518,  57.5899273 ,  58.49682992,  49.92523123,
        55.26392245,  47.50945773,  43.06261613,  51.66986327,
        44.10872866,  57.06458497,  45.18470846,  57.30782477,
        51.00714361,  49.5549909 ,  52.76311802,  44.84354973,
        47.92346592,  53.24668914,  52.98918888,  46.59007153,
        46.42781841,  61.4135158 ,  43.97423285,  46.41986377,
        45.45805028,  53.81550682,  46.24411828,  53.73343546,
        56.94909103,  48.15438284,  69.34259645,  46.60484248,
        58.63786999,  47.42637474,  51.16922842,  52.63616772,
        43.1461815 ,  45.41942857,  51.72778493,  54.16159151,
        81.82617191,  46.33185812,  46.52134208,  57.8704972 ,
        44.97465173,  71.7847269 ,  45.86313238,  44.36422785,
        44.71201199,  55.162472  ,  47.0161211 ,  65.48747903,
        57.9591503 ,  57.14153901,  63.91353926,  55.80790201,
        46.39572181,  50.67718497,  49.51987354,  47.57592871,
        46.40018458,  54.1361996 ,  45.36908306,  44.81851648,
        47.95570889,  59.99177892,  85.25030289])

In [6]:
y_test

unique_id
346-2020-21    50.0
60-2021-22     50.0
323-2018-19    45.0
40-2018-19     55.0
58-2018-19     50.0
               ...
416-2022-23    45.0
473-2022-23    50.0
31-2018-19     50.0
284-2018-19    55.0
141-2021-22    85.0
Name: target_value, Length: 283, dtype: float64

In [7]:
y_pred_train = model.predict(X_train)

# Calculate the mean squared error to evaluate the model's performance
mse = mean_squared_error(y_train, y_pred_train)
print(f"Mean Squared Error: {mse}")

Mean Squared Error: 4.091483048246382

In [8]:
print(y_test)

unique_id
346-2020-21    50.0
60-2021-22     50.0
323-2018-19    45.0
40-2018-19     55.0
58-2018-19     50.0
               ...
416-2022-23    45.0
473-2022-23    50.0
31-2018-19     50.0
284-2018-19    55.0
141-2021-22    85.0
Name: target_value, Length: 283, dtype: float64

In [9]:
with open('../models/catboost_v0.0.1.pkl', 'wb') as file:
    pickle.dump(model, file)

In [10]:
# Load the saved model from the pickle file
with open('../models/catboost_v0.0.1.pkl', 'rb') as file:
    loaded_model = pickle.load(file)